### ISSUE TITLE
Retrieve image name from repo?

### ISSUE THREAD

**Issue by lsetiawan** [uwhackweek/docker-template#1]
There's hardcoding here for example.

https://github.com/uwhackweek/docker-template/blob/0fef9f3ecc3a252d06a3a281d17f9e284e0a835b/.github/workflows/CI.yml#L23

I'm wondering if we can just use the `github.repository` context for the image name? Also assuming that there's an organization by that name in docker hub?

So if repo is `uwescience/snowexhack2021` the image will be exactly the same.

**Comment by scottyhq** [comment]
while i like this idea, it might be hard in practice. i think there are some issues around character limitations (capitalization, dashes, underscores etc).  but i at least created an environment variable at the top of the script so that it's easy to change in one place:

https://github.com/uwhackweek/docker-template/blob/66d080fb9ec045c5d825292ea4dff9891990f3ed/.github/workflows/PR.yml#L11-L12

**Comment by scottyhq** [comment]
actions now read from https://github.com/uwhackweek/docker-template/blob/main/.env
